# Generated by Django 4.2.1 on 2023-05-12 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='categorias')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('duracion', models.IntegerField()),
                ('nivel', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=50)),
                ('lenguajes', models.CharField(max_length=100)),
                ('imagenes', models.ImageField(upload_to='cursos')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('metodos_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('merca', 'Mercadopago'), ('transf', 'Transferencia Bancaria')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='usuarios')),
                ('perfil', models.ImageField(upload_to='perfiles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('impuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bootapp.curso')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bootapp.orden')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bootapp.usuario'),
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('duracion', models.IntegerField()),
                ('tipo', models.CharField(choices=[('video', 'Video'), ('texto', 'Texto'), ('document', 'Documentos'), ('link', 'Enlaces')], max_length=10)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bootapp.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bootapp.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bootapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuentos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direccion_factura', models.CharField(max_length=100)),
                ('moneda', models.CharField(max_length=10)),
                ('numero_factura', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bootapp.orden')),
            ],
        ),
        migrations.CreateModel(
            name='CursoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bootapp.categoria')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bootapp.curso')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='categorias',
            field=models.ManyToManyField(through='bootapp.CursoCategoria', to='bootapp.categoria'),
        ),
    ]
