# Generated by Django 4.2.1 on 2023-05-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootapp', '0002_alter_categoria_table_alter_curso_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagenes',
            field=models.CharField(max_length=200),
        ),
    ]
