/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 14-nov.-2022 21:17:30 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Curso` CASCADE
;

DROP TABLE IF EXISTS `Factura` CASCADE
;

DROP TABLE IF EXISTS `Lecciones` CASCADE
;

DROP TABLE IF EXISTS `Usuario` CASCADE
;

DROP TABLE IF EXISTS `UsuarioCurso` CASCADE
;

/* Create Tables */

CREATE TABLE `Curso`
(
	`Id` INT NOT NULL AUTO_INCREMENT,
	`Nombre` VARCHAR(50) NULL,
	`Descripcion` VARCHAR(50) NULL,
	`Costo` FLOAT(10,2) NULL,
	`Calificacion` INT NULL,
	`Comentarios` VARCHAR(50) NULL,
	`Nivel` INT NULL,
	`Lenguaje` VARCHAR(50) NULL,
	`NoLecciones` INT NULL,
	`foto` VARCHAR(50) NULL,
	`IsFree` BOOL NULL,
	`idCurso` INT NULL,
	`idUsuasrio` INT NULL,
	CONSTRAINT `PK_Curso` PRIMARY KEY (`Id` ASC)
)
ENGINE=MyISAM

;

CREATE TABLE `Factura`
(
	`Id` int NULL,
	`NFact` int NULL,
	`IdCurso` int NULL,
	`IdUsuario` int NULL,
	`Descripcion` varchar(100) NULL,
	`iva` decimal NULL,
	`subTotal` decimal NULL,
	`Total` decimal NULL,
	`fecha` date NULL,
	`tipo` varchar(2) NULL,
	`tipoMoneda` varchar(2) NULL,
	`MetodoDePago` varchar(2) NULL
)
ENGINE=MyISAM

;

CREATE TABLE `Lecciones`
(
	`Id` INT NOT NULL AUTO_INCREMENT,
	`idCurso` INT UNSIGNED NULL,
	`NoLeccion` INT NULL,
	`urlVideo` VARCHAR(50) NULL,
	`pregreso` INT NULL,
	`apuntesEstudiante` VARCHAR(4) NULL,
	CONSTRAINT `PK_Lecciones` PRIMARY KEY (`Id` ASC)
)
ENGINE=MyISAM

;

CREATE TABLE `Usuario`
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Nombre` VARCHAR(50) NULL,
	`Apellido` VARCHAR(50) NULL,
	`Email` VARCHAR(50) NULL,
	`Edad` INT NULL,
	`UserName` VARCHAR(50) NULL,
	`Contrasena` VARCHAR(50) NULL,
	`foto` VARCHAR(50) NULL,
	`telfijo` VARCHAR(50) NULL,
	`celular` VARCHAR(50) NULL,
	`direccion` VARCHAR(50) NULL,
	`pais` VARCHAR(50) NULL,
	`ciudad` VARCHAR(50) NULL,
	`rol` int NULL,
	`IdCurso` INT NULL,
	`tipo` INT NULL,
	CONSTRAINT `PK_Usuario` PRIMARY KEY (`ID` ASC)
)
ENGINE=MyISAM

;

CREATE TABLE `UsuarioCurso`
(
	`idCurso` INT NOT NULL,
	`idUsuasrio` INT NOT NULL
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `UsuarioCurso` 
 ADD INDEX `IXFK_UsuarioCurso_Curso` (`idCurso` ASC)
;

ALTER TABLE `UsuarioCurso` 
 ADD INDEX `IXFK_UsuarioCurso_Usuario` (`idUsuasrio` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `UsuarioCurso` 
 ADD CONSTRAINT `FK_UsuarioCurso_Curso`
	FOREIGN KEY (`idCurso`) REFERENCES `Curso` (`Id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `UsuarioCurso` 
 ADD CONSTRAINT `FK_UsuarioCurso_Usuario`
	FOREIGN KEY (`idUsuasrio`) REFERENCES `Usuario` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;
